config/routes.rb
Rails.application.routes.draw do
  get '/posts', to: 'posts#index'
  get 'posts/new'
  post 'posts/new', to: 'posts#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/signup', to: 'users#new'

  root to: 'posts#index'

  resources :users, only: [:new, :create, :show]
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_create :generate_token
  validates :name, presence: true, length: { maximum: 25 }, uniqueness: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true

  has_many :posts
  has_secure_password

  def generate_token
    self.remember_token = User.create_token
  end

  def self.create_token
    user_token = SecureRandom.urlsafe_base64
    Digest::SHA1.hexdigest user_token
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def signin(user)
    new_token = User.create_token
    user.update_attributes(remember_token: new_token)
    cookies.permanent[:remember_token] = new_token
    @current_user = user
  end

  def retrive_user
    if cookies[:remember_token]
      User.find_by(remember_token: cookies[:remember_token])
    else
      @current_user = nil
    end
  end

  def current_user
    @current_user ||= retrive_user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  helper_method :current_user
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  # include post_helper

  before_action :logged_in_user, only: %i[create new]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @user = current_user
    if @user.posts.build(post_params).save
      redirect_to posts_path
    else
      flash.now[:error] = 'Error saving the post'
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  # rubocop:disable Style/GuardClause
  def logged_in_user
    unless logged_in?
      flash[:error] = 'Please log in to see this'
      redirect_to login_path
    end
  end
  # rubocop:enable Style/GuardClause

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    @session
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user&.authenticate(params[:session][:password])
      signin(@user)
      redirect_to posts_path
    else
      flash.now[:error] = 'Incorrect email or password'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password_confirmation = params[:user][:password]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  # def logged_in?
  #   !current_user.nil?
  # end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="top-nav">
    <ul>
    <li><%= link_to 'Posts', posts_path %></li>
<% if current_user %>
        <li>
            Logged-in as: <%= current_user.name.capitalize %>
        </li>
        <li>
            <%= link_to 'log me out',logout_path, method: :delete %>
        </li>
<% else %>
        <li>
            <%= link_to 'Log-in',login_path, method: :get %>
        </li>
<% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Microverse506MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <% flash.each do |key, val| %>
      <div class="alert alert-<%= key %>"><%= val %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All Posts <%= @posts&.count %></h1>

<% if current_user %>
    <strong><%= link_to 'Write a new post', posts_new_path %></strong>
<% else %>
    <strong><%= link_to 'Login to write a post', login_path %></strong>
<% end %>


<% @posts&.each do |post| %>
    <h3> 
        <%= post.title %>
    </h3>
    <% if current_user %>
        <small>
            <%= post.user.name.capitalize %>
        </small>
    <% else %>
        <small class="secret">Want to see who wrote this? <%= link_to 'Sign up today...',signup_path, method: :get %></small>
    <% end %>
    <p>
        <%= post.body %>
    </p>
    <hr>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<p>
Write your post bellow
</p>
<%= form_for :post do |f|%>
  <%= f.label :title %>
  <%= f.text_field (:title) %>

  <%= f.label :body %>
  <%= f.text_area :body%>
  <div>
  <%= f.submit 'submit post' %>
  </div>

<% end %>

<strong><%= link_to 'Back', posts_path %></strong>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', posts_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
    
<%= link_to 'Back', posts_path %>